name: front server live
on:
  #pull_request:
  push:
    branches: [main]
    #types: [closed]
    paths:
      - "video/**"

jobs:
  integrate:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: docker login -u ${{secrets.USERNAME_CANISTER}} -p ${{secrets.PASSWORD_CANISTER}} cloud.canister.io:5000
      - run: cd video && npm install && npm run package && docker build -t "cloud.canister.io:5000/msmarcks/sol:latest" .
      - run: docker push cloud.canister.io:5000/msmarcks/sol:latest
      - name: andrewtwydell/ssh
        uses: AndrewTwydell/ssh-workflow@1.0.0
        with:
          # SSH Host
          host: ${{ secrets.SSH_HOST }}
          # User name
          user: ${{ secrets.SSH_USERNAME }}
          # User Password
          password: ${{ secrets.PASSWORD_SSH }}
          # Script to Run
          script: | 
            docker login -u ${{secrets.USERNAME_REPO}} -p ${{secrets.PASSWORD_REPO}} cloud.canister.io:5000
            docker ps -a -q --filter "name=frontapplive" | grep -q . && docker stop frontapplive && docker rm -fv frontapplive && docker image rm cloud.canister.io:5000/msmarcks/sol:latest || echo ""
            docker run --name frontapplive -p "80:80" -d cloud.canister.io:5000/msmarcks/sol:latest
            exit      